#!/bin/bash

set -o pipefail # Not supported by POSIX shell
set -o errexit
trap "trap - HUP && kill -s SIGHUP -$$" INT HUP TERM EXIT

GATEWAY=backup
mc alias set $GATEWAY $HOSTNAME $USER_ID $PASSWORD

SUBCMD=$1
case $SUBCMD in
	capture)
		DATABASE_URI=$2
		BACKUP_PATH=$3
		mongodump --archive --gzip --uri=$DATABASE_URI | mc pipe "$GATEWAY/$BACKUP_PATH"
	;;
	restore)
		BACKUP_PATH=$2
		DATABASE_URI=$3
		mc cat "$GATEWAY/$BACKUP_PATH" | mongorestore --archive --gzip --uri=$DATABASE_URI
    ;;
	*)
		exit 1
	;;
esac
